name: Pacer
options:
  bundleIdPrefix: com.objp
  deploymentTarget:
    watchOS: 10.0

targets:
  Pacer:
    type: application
    platform: watchOS
    sources: [Pacer]
    entitlements:
      path: Pacer/Pacer.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    info:
      path: Pacer/Info.plist
      properties:
        WKApplication: true
        WKWatchOnly: true
        NSHealthShareUsageDescription: "Pacer reads your heart rate during workouts to display real-time heart rate zones."
        NSHealthUpdateUsageDescription: "Pacer saves your completed workouts to the Health app."
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.objp.Pacer
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: ${PACER_TEAM_ID}
        Release:
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: ${PACER_TEAM_ID}
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "match AdHoc com.objp.Pacer"
  PacerTests:
    type: bundle.unit-test
    platform: watchOS
    sources: [PacerTests]
    dependencies:
      - target: Pacer
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
